#!/usr/bin/env ansible-playbook
---

- name: "Show debug info"
  hosts:
    - master
    - workers
  become: yes
  tasks:
    - name: "Show nodes info"
      debug: var=hostvars[inventory_hostname]
      when: debug|bool

    - name: UnInstall prometheus-node-exporter
      apt:
        name: prometheus-node-exporter
        state: absent

    - name: Stop blackbox-exporter container
      docker_container:
        name: blackbox-exporter
        state: absent

    - name: Stop alertmanager container
      docker_container:
        name: alertmanager
        state: absent

    - name: Stop grafana container
      docker_container:
        name: grafana
        state: absent

    - name: Stop prometheus container
      docker_container:
        name: prometheus
        state: absent

    - name: Tidy up directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/prometheus
        - /etc/grafana
        - /etc/alertmanager
        - /prometheus

    - name: Reset node
      shell: /usr/bin/kubeadm reset --force
      ignore_errors: true

    - name: Flush all chains
      shell: /sbin/iptables -F

    - name: Flush nat
      shell: /sbin/iptables -t nat -F

    - name: Flush mangle
      shell: /sbin/iptables -t mangle -F

    - name: Delete all chains
      shell: /sbin/iptables -X

    - name: Purge kubelet
      apt:
        name: kubelet
        state: absent
        purge: yes
